### ISSUE TITLE
Suggestion - Use uuid's instead of player names for the data management

### ISSUE THREAD

**Issue by ReportCardsMC** [TheRealFrostedWeFall/Vile#8]
title said it all

**Comment by LewisP2018** [comment]
@RileyDatLord, Awaiting FrostedWeFall's response.

**Comment by TheRealFrostedWeFall** [comment]
Could you please make a pull request changing player variables to "uuid of player" variables

**Comment by LewisP2018** [comment]
**Closed.**

**Comment by ReportCardsMC** [comment]
If I made a pull request every user's stats would be reset
